name: Build the application
runs-on: ubuntu-latest
steps:
  - name: Setup JDK 17
    uses: actions/setup-java@v3
    with:
      distribution: 'corretto'
      java-version: 17

  - name: Build the application
    run: |
      mvn clean
      mvn -B package --file pom.xml
