name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        uses: ./.github/workflows/test.yml

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the application
        uses: ./.github/workflows/build.yml
